image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
          - bash ./gradlew -PMAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN check
  tags:
    '*':
      - step:
          script:
            - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
            - tagname=$(git describe --tags --abbrev=0)
            - bash ./gradlew assembleRelease -PMAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN -PRELEASE_KEY_PASSWORD=$RELEASE_KEY_PASSWORD -PRELEASE_STORE_PASSWORD=$RELEASE_STORE_PASSWORD
            - cp app/build/outputs/apk/release/app-release.apk maly-poszukiwacz-skarbow-$tagname.apk
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "maly-poszukiwacz-skarbow-$tagname.apk"
