image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - bash ./gradlew check
  branches:
    '*':
      -step:
        script:
          - bash ./gradlew assembleRelease -PRELEASE_KEY_PASSWORD=$RELEASE_KEY_PASSWORD -PRELEASE_STORE_PASSWORD=$RELEASE_STORE_PASSWORD
