image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - bash ./gradlew check
  tags:
    '*':
      - step:
          script:
            - tagname=$(git describe --tags --abbrev=0)
            - echo $tagname
