image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - bash ./gradlew check
  tags:
    '*':
      - step:
          script:
            -
  branches:
    '*':
      - step:
          script:
            - bash ./gradlew assembleRelease -PRELEASE_KEY_PASSWORD=$RELEASE_KEY_PASSWORD -PRELEASE_STORE_PASSWORD=$RELEASE_STORE_PASSWORD
            - bash cp app/build/outputs/apk/release/app-release.apk maly
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "app/build/outputs/apk/release/app-release.apk"

export BITBUCKET_USERNAME="marian.jureczko@gmail.com"
export BITBUCKET_REPO_OWNER="MarianJureczko"
export BITBUCKET_APP_PASSWORD="ZxNq2ymAHANEVQCRQBkg"
export BITBUCKET_REPO_SLUG="maly-poszukiwacz-skarbow"
curl -X POST "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"app/build/outputs/apk/debug/application.apk"