image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        script:
          - bash ./gradlew check
  branches:
    '*':
      - step:
          script:
            - bash ./gradlew assembleRelease -PRELEASE_KEY_PASSWORD=$RELEASE_KEY_PASSWORD -PRELEASE_STORE_PASSWORD=$RELEASE_STORE_PASSWORD
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "app/build/outputs/apk/release/app-release.apk"
