sequenceDiagram
    Start ->>+ PermissionActivity: onRequestPermissionsResult(requestCode,permissions,grantResults)
    PermissionActivity ->>+ PermissionManager: handleRequestPermissionsResult(:PermissionsSpec,permissions,grantResults)
    alt are all permissions granted
        PermissionManager ->>+ PermissionListener: permissionsGranted(:PermissionsSpec)
        PermissionListener ->>+ PermissionActivity: onPermissionsGranted(:PermissionsSpec)
        PermissionActivity -->>- PermissionListener: x
        PermissionListener -->>- PermissionManager: x
    else
        PermissionManager ->>+ ActivityCompat: shouldShowRequestPermissionRationale(deniedPermission)
        alt should show rationale
            PermissionManager ->>+ PermissionManager: showPermissionRationaleDialog(:PermissionsSpec)
            PermissionManager ->>+  PermissionListener: retry()
            PermissionListener -->>- PermissionManager: x
            PermissionManager -->>- PermissionManager: x
        else
            PermissionManager ->>+ PermissionManager: showPermissionPermanentDenialDialog(:PermissionsSpec,deniedPermission)
            opt user wants to change permissions in settings
                PermissionManager ->>+ PermissionListener: navigateToSettings()
                PermissionListener ->> Settings: startActivity(intent)
                Settings --> PermissionListener: x
                PermissionListener -->>- PermissionManager: x
            end
            PermissionManager -->>- PermissionManager: x
        end
        ActivityCompat -->>- PermissionManager: x
    end
    PermissionManager -->>- PermissionActivity: x
    PermissionActivity -->>- Start: x
    Settings ->>+ PermissionActivity: onResume()
    PermissionActivity ->>+ PermissionManager: handleResume()
    PermissionManager -->>- PermissionActivity: x
