sequenceDiagram
    Start ->>+ XyzActivity: onCreate()
    XyzActivity ->>+ PermissionActivity: assurePermissionsAreGranted(:PermissionsSpec)
    PermissionActivity ->>+ PermissionsSpec: getPermissionWithCodeArray()
    PermissionsSpec -->>- PermissionActivity: x
    PermissionActivity ->>+ PermissionManager: areAllPermissionsGranted(:Array<PermissionWithCode>)
    PermissionManager -->>- PermissionActivity: x
    PermissionActivity -->>- XyzActivity: x
    XyzActivity -->>- Start: x