stateDiagram-v2
    [*] --> MainActivity
    MainActivity --> TreasuresEditorActivity : create new route\n OR\n edit existing route
    TreasuresEditorActivity --> MainActivity
    MainActivity --> BluetoothActivity : send route\n OR\n receive route
    BluetoothActivity --> MainActivity
    MainActivity --> SearchingActivity : select route\n for searching
    SearchingActivity --> MainActivity
    SearchingActivity --> TreasureSelectorActivity : select treasure\n for searching
    TreasureSelectorActivity --> SearchingActivity
    SearchingActivity --> PhotoActivity : show photo hint
    PhotoActivity --> SearchingActivity
    SearchingActivity --> ResultActivity : show treasure
    ResultActivity --> SearchingActivity
    SearchingActivity --> QrScanIntent : scan found treasure
    QrScanIntent --> SearchingActivity
    TreasuresEditorActivity --> CapturePhotoIntent : make photo\n with a hint
    CapturePhotoIntent --> TreasuresEditorActivity
    SearchingActivity --> MapActivity : show map
    MapActivity --> SearchingActivity

    note right of QrScanIntent: INTENT
    note right of CapturePhotoIntent: INTENT
