sequenceDiagram
    Start ->>+ XyzActivity: onCreate()
    XyzActivity ->>+ PermissionActivity: assurePermissionsAreGranted(:PermissionsSpec)
    PermissionActivity ->>+ PermissionsSpec: getPermissionWithCodeArray()
    PermissionsSpec -->>- PermissionActivity: x
    PermissionActivity ->>+ PermissionManager: areAllPermissionsGranted(:Array<PermissionWithCode>)
    PermissionManager -->>- PermissionActivity: x
    alt all permissions granted
        PermissionActivity ->>+ XyzActivity: onPermissionsGranted()
        XyzActivity -->>- PermissionActivity: x
    else
        PermissionActivity ->>+ PermissionManager: requestAllPermissions(:PermissionsSpec)
        PermissionManager ->>+ PermissionsSpec: getPermissionWithCodeArray()
        PermissionsSpec -->>- PermissionManager: x
        PermissionManager ->>+ ActivityCompat: requestPermissions(permissions,requestCode)
        ActivityCompat -->>- PermissionManager: x
        PermissionManager -->>- PermissionActivity: x
    end
    PermissionActivity -->>- XyzActivity: x
    XyzActivity -->>- Start: x